Fix regression introduced in c51c9c7
Not all nodes might be on the storage network anymore, so we could crash
with:

Exception undefined method `[]' for nil:NilClass /opt/dell/crowbar_framework/app/models/ceph_service.rb:117:in `apply_role_pre_chef_call'
/opt/dell/crowbar_framework/app/models/service_object.rb:1213:in `apply_role'
/opt/dell/crowbar_framework/app/models/service_object.rb:1535:in `active_update'
/opt/dell/crowbar_framework/app/models/service_object.rb:726:in `proposal_commit'
/opt/dell/crowbar_framework/app/controllers/barclamp_controller.rb:391:in `proposal_update'